//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSQLApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_TUKOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_TUKOR()
        {
            this.F_NAPLO = new HashSet<F_NAPLO>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> ERVDATTOL { get; set; }
        public Nullable<System.DateTime> ERVDATIG { get; set; }
        public string SZAM { get; set; }
        public string MEGN { get; set; }
        public int FOKIV { get; set; }
        public string KTGSZAM { get; set; }
        public string NYITOSZLA { get; set; }
        public Nullable<int> X_MSZID { get; set; }
        public string KELLMSZAM { get; set; }
        public string SZAM2 { get; set; }
        public string MEGN2 { get; set; }
        public string SZAM3 { get; set; }
        public string MEGN3 { get; set; }
        public string SZAM4 { get; set; }
        public string MEGN4 { get; set; }
        public Nullable<int> KEZELOID { get; set; }
        public Nullable<int> x_devid { get; set; }
        public string atvmirol { get; set; }
        public string atvmire { get; set; }
        public string MszBevKiad { get; set; }
        public string AfaMukKod { get; set; }
        public string NemKellBankMegbizas { get; set; }
        public string Inaktiv { get; set; }
        public Nullable<System.DateTime> Datumtol { get; set; }
        public string Afakod { get; set; }
        public string HostName { get; set; }
        public string SystemUser { get; set; }
        public string AppName { get; set; }
        public string ProcName { get; set; }
        public string DevizaErtekeles { get; set; }
        public string DevEgyenlegAtert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_NAPLO> F_NAPLO { get; set; }
    }
}
