//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSQLApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoCompSysElesEntities : DbContext
    {
        public DemoCompSysElesEntities()
            : base("name=DemoCompSysElesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<F_NAPLO> F_NAPLO { get; set; }
        public virtual DbSet<F_TUKOR> F_TUKOR { get; set; }
        public virtual DbSet<X_PARTNER> X_PARTNER { get; set; }
        public virtual DbSet<x_Param> x_Param { get; set; }
    }
}
