//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSQLApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_Param
    {
        public int id { get; set; }
        public string Param { get; set; }
        public string Ertek { get; set; }
        public System.DateTime Ervdattol { get; set; }
        public Nullable<System.DateTime> Ervdatig { get; set; }
        public string Megj { get; set; }
        public string UserParam { get; set; }
    }
}
