//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSQLApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_PARTNER
    {
        public int ID { get; set; }
        public Nullable<int> X_VALLALATID { get; set; }
        public string PARTCSOP { get; set; }
        public string KOD { get; set; }
        public string ADOSZAM { get; set; }
        public string MEGN { get; set; }
        public string TELEFON { get; set; }
        public string FAX { get; set; }
        public string EMIL { get; set; }
        public string WEB { get; set; }
        public string ORSZAG { get; set; }
        public string IRSZ { get; set; }
        public string VAROS { get; set; }
        public string UTCA { get; set; }
        public string UGYINT { get; set; }
        public string UGYINTTEL { get; set; }
        public string ARFORMA { get; set; }
        public Nullable<System.DateTime> ERVDATTOL { get; set; }
        public Nullable<System.DateTime> ERVDATIG { get; set; }
        public string BANKSZLA { get; set; }
        public Nullable<int> kezeloid { get; set; }
        public string vevofsz { get; set; }
        public string szallfsz { get; set; }
        public Nullable<int> esednap { get; set; }
        public Nullable<decimal> kedvezm { get; set; }
        public string korrkod { get; set; }
        public Nullable<int> fizdatjel { get; set; }
        public string lev_utca { get; set; }
        public string fizmod { get; set; }
        public string ugynokkod { get; set; }
        public Nullable<int> szlapeld { get; set; }
        public string felettes { get; set; }
        public Nullable<int> KM { get; set; }
        public string CEGVEZ { get; set; }
        public string CEGVTEL { get; set; }
        public string FOKONY { get; set; }
        public string FOKOTEL { get; set; }
        public string PUVEZ { get; set; }
        public string PUVETEL { get; set; }
        public string BERO { get; set; }
        public string BEROTEL { get; set; }
        public string SBANKSZ { get; set; }
        public string SZTP { get; set; }
        public string DEV { get; set; }
        public string SZLANYELV { get; set; }
        public Nullable<decimal> KEDV { get; set; }
        public string lev_irsz { get; set; }
        public string lev_varos { get; set; }
        public Nullable<int> x_devid { get; set; }
        public string pazonok { get; set; }
        public string forras { get; set; }
        public string Megye { get; set; }
        public string Megj { get; set; }
        public string Erdemi { get; set; }
        public string Tulajdonsag { get; set; }
        public string CegvMobil { get; set; }
        public string KontaktNev { get; set; }
        public string KontaktTel { get; set; }
        public string KontaktMobil { get; set; }
        public string TevKor1 { get; set; }
        public string TevKor2 { get; set; }
        public string TevKor3 { get; set; }
        public string TevKor4 { get; set; }
        public string TevKor5 { get; set; }
        public Nullable<int> x_vallalat_id { get; set; }
        public string megn1 { get; set; }
        public string megn2 { get; set; }
        public string email { get; set; }
        public string ugynok { get; set; }
        public string lev_megn { get; set; }
        public string EUAdoszam { get; set; }
        public string Cegjegyzekszam { get; set; }
        public string Mubiz { get; set; }
        public string legjobbar { get; set; }
        public string megjegyzes { get; set; }
        public string csoport1 { get; set; }
        public string csoport2 { get; set; }
        public string csoport3 { get; set; }
        public string AnyacegADOSZAM { get; set; }
        public string AnyacegEUADOSZAM { get; set; }
        public string FFNemKell { get; set; }
        public string Mszam { get; set; }
        public string NemKellBankMegbizas { get; set; }
        public Nullable<int> Aktiv { get; set; }
        public Nullable<int> TurelmiIdo { get; set; }
        public string BelsoPartner { get; set; }
        public string GLN_UNB_delivery_address { get; set; }
        public string GLN_delivery_address { get; set; }
        public string GLN_invoice_address { get; set; }
        public string Partnerkodom { get; set; }
        public string KonyveloirodaPartnerkod { get; set; }
        public Nullable<int> XMAgazatId { get; set; }
        public string AdoAzon { get; set; }
        public string OstermIgSzam { get; set; }
        public string OstermRegSzam { get; set; }
        public string HostName { get; set; }
        public string SystemUser { get; set; }
        public string AppName { get; set; }
        public string ProcName { get; set; }
        public Nullable<int> SzemelyId { get; set; }
        public Nullable<int> Statusz { get; set; }
        public Nullable<int> Prioritas { get; set; }
        public string MszamEleje { get; set; }
        public Nullable<int> Letszam { get; set; }
        public Nullable<System.DateTime> SzerzKapcsKezd { get; set; }
        public string KeszlFokSzam { get; set; }
        public string ElabeFokSzam { get; set; }
        public string NAVXMLIrsz { get; set; }
        public string NAVXMLTelepules { get; set; }
        public string NAVXMLKerulet { get; set; }
        public string NAVXMLKozterNev { get; set; }
        public string NAVXMLKozterJel { get; set; }
        public string NAVXMLHazszam { get; set; }
        public string NAVXMLEpulet { get; set; }
        public string NAVXMLLepcsohaz { get; set; }
        public string NAVXMLSzint { get; set; }
        public string NAVXMLAjto { get; set; }
        public Nullable<System.DateTime> NAVXMLCimbont { get; set; }
        public string SzlaPostaUA { get; set; }
        public string SzlaEmail { get; set; }
        public string sz_irsz { get; set; }
        public string sz_varos { get; set; }
        public string sz_utca { get; set; }
        public string CsoportAdoszam { get; set; }
    }
}
